const añosVida = 33;
undefined;
const horasDía = 24;
undefined;
const diasAño = 365;
undefined;
const total = horasDia * diasAño;
const total = horasDía * diasAño;
undefined;
total;
8760;
const totalTotal = total * añosVida;
undefined;
totalTotal;
289080;
